spring:
  application:
    name: plazoletarestaurants
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:mysql://localhost:3306/plazoleta_restaurants?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: false

server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

app:
  jwt:
    secret: ${JWT_SECRET}

logging:
  level:
    root: INFO
    com.pragma.plazoletarestaurants: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

appDescription: "Plazoleta Restaurants App"
appVersion: "1.0.0"

services:
  users:
    url: http://localhost:8080
  notifications:
    url: http://localhost:8082
  traceability:
    url: http://localhost:8083